export { default as Header } from './header/';
export { default as Card } from './card/';
export { HeaderTag as HeaderTag } from './title/';
export { ProjectsTag as ProjectsTag } from './title/';
export { LanguagesTag as LanguagesTag } from './title/';
export { AboutMeTag as AboutMeTag} from './title/';
export { default as Languages } from './languages/';
export { default as Footer } from './footer/';
export { default as SocialMedia } from './media/';
export { default as EmailButton } from './side-email/';
export { default as AboutMe } from './about-me/';
